### ISSUE TITLE
Argument in 04-dockerfile-with-build-arguments does not behave like a bash variable

### ISSUE THREAD

**Issue by PedroAS7** [heig-vd-dai-course/heig-vd-dai-course-code-examples#13]
Dockerfile example number 4, named "04-dockerfile-with-build-arguments", uses `ARG` to output a variable in the `echo` command that is launched when the container is run.

Changing the arg's value in the build command doesn't seem to help either.

The Dockerfile in the example is:
```dockerfile
FROM archlinux:base-20240825.0.257728

# Working directory
WORKDIR /app

# Arguments
ARG MESSAGE="Hello, World!"

# Entrypoint
ENTRYPOINT ["echo"]

# Command to run
CMD ["${MESSAGE}"]
```

Commands (<) and outputs (>):
```
< sudo docker build -t dockerfile-with-build-arguments .
< sudo docker run --name 04 dockerfile-with-build-arguments
> ${MESSAGE}
< sudo docker rm 04
< sudo docker image rm dockerfile-with-build-arguments
< sudo docker build -t dockerfile-with-build-arguments --build-arg MESSAGE="Hello, DAI student!" .
< sudo docker run --name 04 dockerfile-with-build-arguments
> ${MESSAGE}
```

**Comment by ludelafo** [comment]
Thank you very much!

After some tinkering, I wasn't able to illustrate how to use build arguments with my initial example so I decided to change it with a new simple one that you can find in the mentioned pull request.

I tested it on my computer and it works without any issues now and should still be simple enough to understand it without much trouble
